### ISSUE TITLE
How is this supposed to be used?

### ISSUE THREAD

**Issue by estahn** [inuits/mkdocs-factsheet#2]

**Comment by carroarmato0** [comment]
Hi @estahn, I don't have experience with this myself, but I can give you something that looks like a code example:

In your main mkdocs.yml file:
```
plugins:
  - factsheet:
    sheets:
      'guacamole/*': docs/guacamole/guacamole.yaml
```

The guacamole.yaml file in questions:
```
components:
  backend:
    name: Symfony backend
    docs-link: /guacamole/backend/
    tracker: https://some-issue-tracker/projects/guacamole
    repository: [guacamole/guacamole-webapp, guacamole/guacamole-webapp-v1]

  websockets:
    name: Crossbar proxy
    docs-link: /guacamole/brokers/websockets/
    tracker: https://some-issue-tracker/projects/guacamole
    repository: guacamole/guacamole-ws-server
```
